version: '3.8'

services:

    grafana:
        image: grafana/grafana:${GRAFANA_VERSION:-latest}
        hostname: grafana
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
            GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
        volumes:
            - "./volumes/grafana:/var/lib/grafana"
        networks:
            - ${GLOBAL_NETWORK:-grafana}

    prometheus:
        image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
        hostname: prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
            - "./volumes/prometheus:/prometheus"
        networks:
            - ${GLOBAL_NETWORK:-prometheus}
