version: '3.8'

services:

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: 'postgres'
        volumes:
            - "./volumes/postgres/data:/var/lib/postgresql/data"
        networks:
            - ${GLOBAL_NETWORK:-postgres}
