version: '3.8'

services:

    negozio-order-service:
        image: anatolydudko/negozio-order-service:${APP_VERSION:-demo}
        hostname: negozio-order-service
        container_name: negozio-order-service
        ports:
            - "8181:8181"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
        networks:
            - ${GLOBAL_NETWORK:-service}

    negozio-payment-service:
        image: anatolydudko/negozio-payment-service:${APP_VERSION:-demo}
        hostname: negozio-payment-service
        container_name: negozio-payment-service
        ports:
            - "8182:8182"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
        networks:
            - ${GLOBAL_NETWORK:-service}

    negozio-department-service:
        image: anatolydudko/negozio-department-service:${APP_VERSION:-demo}
        hostname: negozio-department-service
        container_name: negozio-department-service
        ports:
            - "8183:8183"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=department&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
            KAFKA-CONFIG_BOOTSTRAP-SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
            KAFKA-CONFIG_SCHEMA-REGISTRY-URL: http://schema-registry:8081
        networks:
            - ${GLOBAL_NETWORK:-service}