spring.application.name=negozio
server.address=0.0.0.0
server.port=8081

spring.docker.compose.enabled=false

# for docker container
#spring.datasource.url=jdbc:postgresql://db:5432/negozio
# for local build
spring.datasource.url=jdbc:postgresql://localhost:5432/negozio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# https://emn178.github.io/online-tools/sha256.html
app.jwt-secret=52aac57d57ebcc20ed330c0188e9a6923c447ff4301495d2284e056b0c0c62ec
# 7 days
app.jwt-expiration-milliseconds=604800000