version: '3.8'

services:

    init-postgres:
        image: anatolydudko/negozio-db-migrator:${APP_VERSION:-demo}
        container_name: negozio-db-migrator
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
            DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
        networks:
            - ${GLOBAL_NETWORK:-service}