version: "3.8"

services:

    negozio-customer-web-client-v1:
        image: anatolydudko/negozio-customer-web-client-v1:demo
        hostname: web-client
        container_name: web-client
        restart: always
        build:
            context: negozio-customer-web-client-v1
            dockerfile: Dockerfile-prod
        environment:
            VITE_ORDER_SERVICE: http://localhost:8181
            VITE_DEPARTMENT_SERVICE: http://localhost:8183
            VITE_CUSTOMER_SERVICE: http://localhost:8184
            VITE_DEPARTMENT_ID: d215b5f8-0249-4dc5-89a3-51fd148cfb45
            VITE_CURRENCY: €
        ports:
            - "8080:8080"
